version: "3.8"
services:
  laravel-db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel_bd
      MYSQL_USER: usr_laraver
      MYSQL_PASSWORD: Usr.db.2023
    ports:
      - 33069:3306
    volumes:
      - ./database/schemas/:/var/lib/mysql
    networks:
      laravel_prod_net:
        ipv4_address: 173.16.100.9

  laravel-prod:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 8200:80
    volumes:
      - ./example-prod:/var/www/
      - ./example-prod/public:/var/www/html
    networks:
      laravel_prod_net:
        ipv4_address: 173.16.100.10
    depends_on:
      - laravel-db

volumes:
  example-prod:
  database:

networks:
  laravel_prod_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 173.16.100.0/24