version: "3.8"
services:
  php:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: php72
    restart: always
    ports:
      - 72:80
    volumes:
      - ./html:/var/www/html
      # - ./config:/usr/local/etc/php 
volumes:
  html: {}
  # config: {}