version: '3.8'
services:
  postgres-db:
    container_name: postgres_DB
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=dataBase
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    networks:
      drupal_prod_net:
        ipv4_address: 173.16.100.11

  drupal:
    image: drupal:latest
    ports:
      - "8080:80"
    volumes:
      - drupal_data:/var/www/html
    environment:
      - DRUPAL_DATABASE_HOST=postgres-db
      - DRUPAL_DATABASE_PORT=5432
      - DRUPAL_DATABASE_NAME=dataBase
      - DRUPAL_DATABASE_USER=root
      - DRUPAL_DATABASE_PASSWORD=root
    networks:
      drupal_prod_net:
        ipv4_address: 173.16.100.10
    depends_on:
      - postgres-db

volumes:
  drupal_data:

networks:
  drupal_prod_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 173.16.100.0/24
