version: "3.8"

services:
  postgres-db:
    container_name: postgres_DB
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      - DATABASE_HOST=postgres-db  
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=DB
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    networks:
      red_postgresql:
        ipv4_address: 173.16.101.11  

volumes:
  postgres-data:

networks:
  red_postgresql:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 173.16.101.0/24  
