# Utiliza una imagen base de Drupal
FROM drupal:latest

# Instala la extensión pg_trgm
RUN apt-get update && apt-get install -y postgresql-contrib

# Indica que la imagen se basa en drupal:latest
FROM drupal:latest

# Resto de las configuraciones del Dockerfile
# ...
