version: "3.8"

services:
  postgres-db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      - DATABASE_HOST=127.0.0.1
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=db_example
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    networks:
      laravel_prod_net:
        ipv4_address: 173.16.100.11

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - "5050:80"
    networks:
      laravel_prod_net:
        ipv4_address: 173.16.100.12      
    depends_on:
      - postgres-db

  laravel-prod:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 8200:80
    volumes:
      - ./apiRestful:/var/www/
      - ./apiRestful/public:/var/www/html
      # SE Crea esta carpeta #
      # URL/ mkdir config
      #sudo docker cp macheneNameId:/usr/local/etc/php ./config
      # Descomentar y se tiene que construir para ver los cambios #
      # - ./config:/usr/local/etc/php 
    networks:
      laravel_prod_net:
        ipv4_address: 173.16.100.10
    depends_on:
      - postgres-db

volumes:
  apiRestful:
  postgres-data:
  config:

networks:
  laravel_prod_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 173.16.100.0/24
